export const sourceAssets = {
  wikaIdle: "characters/wika/wika_idle.png",
  wikaRun: "characters/wika/wika_run.png",
  wikaJump: "characters/wika/wika_jump.png",
  wikaHappy: "characters/wika/wika_happy.png",
  wikaWave: "characters/wika/wika_wave.png",
  michalIdle: "characters/michal/michal_idle.png",
  michalBouquet: "characters/michal/michal_bouquet.png",
  michalWave: "characters/michal/michal_wave.png",
  heart: "items/hearts/heart_medium.png",
  bigHeart: "items/hearts/heart_big.png",
  broken: "items/hearts/heart_broken.png",
  gift: "items/gifts/gift_box.png",
  bouquet: "items/gifts/bouquet_roses.png",
  letter: "items/collectibles/love_letter.png",
  coffee: "items/collectibles/love_coffee.png",
  ticket: "items/collectibles/ticket_pink.png",
  star: "items/collectibles/gold_star.png",
  key: "items/collectibles/heart_key.png",
  hedge: "world/maze/hedge_horizontal.png",
  hedgeVertical: "world/maze/hedge_vertical.png",
  gate: "world/maze/maze_finish_gate.png",
  platform: "world/platforms/platform_long.png",
  crate: "world/platforms/crate.png",
  flag: "world/platforms/finish_flag.png",
  cloud: "world/decor/cloud_big.png",
  village: "world/decor/village_bg.png",
  arch: "world/decor/flower_arch.png",
  left: "ui/btn_left.png",
  right: "ui/btn_right.png",
  jump: "ui/btn_jump.png",
};
const optimizedAssets = Object.fromEntries(
  Object.entries(sourceAssets).map(([key, path]) => [
    key,
    "assets/optimized/" + path.replace(/\.png$/, ".webp"),
  ]),
);
export const snakeAssets = {
  snakeHead: "assets/snake/characters/wika_head.webp",
  snakeBody: "assets/snake/snake/snake_body.webp",
  snakeTail: "assets/snake/snake/snake_tail.webp",
  snakeHeart: "assets/snake/items/heart.webp",
  snakeBouquet: "assets/snake/items/bouquet.webp",
  snakeGift: "assets/snake/items/gift.webp",
  snakeBroken: "assets/snake/items/broken_heart.webp",
  snakeDark: "assets/snake/items/dark_heart.webp",
  snakeUp: "assets/snake/ui/btn_up.webp",
  snakeDown: "assets/snake/ui/btn_down.webp",
  snakeLeft: "assets/snake/ui/btn_left.webp",
  snakeRight: "assets/snake/ui/btn_right.webp",
};
export const dashAssets = {
  coverCatcher: "assets/dash/covers/01_serduszkowy_zbieracz_cover.webp",
  coverMaze: "assets/dash/covers/02_milosny_labirynt_cover.webp",
  coverDash: "assets/dash/covers/03_wika_dash_cover.webp",
  coverMemory: "assets/dash/covers/04_memory_wspomnien_cover.webp",
  coverGift: "assets/dash/covers/05_magiczny_prezent_cover.webp",
  coverSnake: "assets/dash/covers/06_love_snake_cover.webp",
  dashRun: "assets/dash/characters/wika_dash_run.webp",
  dashJump: "assets/dash/characters/wika_dash_jump.webp",
  dashCrouch: "assets/dash/characters/wika_dash_crouch.webp",
  dashRiverside: "assets/dash/backgrounds/wika_dash_bg_riverside_sunset.webp",
  dashValley: "assets/dash/backgrounds/wika_dash_bg_hearts_valley.webp",
  dashPlatform: "assets/dash/tiles/platform_flower_tile.webp",
  dashBird: "assets/dash/obstacles/bird_mail.webp",
  dashCrate: "assets/dash/obstacles/crate_heart.webp",
  dashHeart: "assets/dash/items/heart_collectible.webp",
  dashJumpButton: "assets/dash/ui/btn_jump.webp",
  dashCrouchButton: "assets/dash/ui/btn_crouch.webp",
  dashPauseButton: "assets/dash/ui/btn_pause.webp",
  dashBackButton: "assets/dash/ui/btn_back.webp",
};
export const duoAssets = {
  duoCover: "assets/duo/v2/cover.webp",
  duoBg1: "assets/duo/backgrounds/background_level_1.webp",
  duoBg2: "assets/duo/backgrounds/background_level_2.webp",
  duoMichalIdle: "assets/duo/characters/michal/michal_idle.webp",
  duoMichalJump: "assets/duo/characters/michal/michal_jump.webp",
  duoMichalPush: "assets/duo/characters/michal/michal_push.webp",
  duoMichalWalk: "assets/duo/characters/michal/michal_walk.webp",
  duoWikaIdle: "assets/duo/v2/wika/wika_idle.webp",
  duoWikaJump: "assets/duo/v2/wika/wika_jump.webp",
  duoWikaPush: "assets/duo/v2/wika/wika_push.webp",
  duoWikaWalk: "assets/duo/v2/wika/wika_walk.webp",
  duoBlueWater: "assets/duo/gameplay/collectibles/blue_water.webp",
  duoDiamondCollectible:
    "assets/duo/gameplay/collectibles/diamond_collectible.webp",
  duoHeartCollectible:
    "assets/duo/gameplay/collectibles/heart_collectible.webp",
  duoPinkLava: "assets/duo/gameplay/collectibles/pink_lava.webp",
  duoDoorBlue: "assets/duo/gameplay/doors/door_blue.webp",
  duoDoorPink: "assets/duo/gameplay/doors/door_pink.webp",
  duoFinalDoor: "assets/duo/gameplay/doors/final_door.webp",
  duoSpikes: "assets/duo/gameplay/hazards/spikes.webp",
  duoBridgePlatform: "assets/duo/gameplay/interactive/bridge_platform.webp",
  duoButtonBlue: "assets/duo/gameplay/interactive/button_blue.webp",
  duoButtonPink: "assets/duo/gameplay/interactive/button_pink.webp",
  duoCrate: "assets/duo/gameplay/interactive/crate.webp",
  duoHeavyBlock: "assets/duo/gameplay/interactive/heavy_block.webp",
  duoLeverBlue: "assets/duo/gameplay/interactive/lever_blue.webp",
  duoLeverPink: "assets/duo/gameplay/interactive/lever_pink.webp",
  duoMovingPlatform: "assets/duo/gameplay/interactive/moving_platform.webp",
  duoPlatformBlock: "assets/duo/gameplay/tiles/platform_block.webp",
  duoPlatformColumn: "assets/duo/gameplay/tiles/platform_column.webp",
  duoPlatformEdge: "assets/duo/gameplay/tiles/platform_edge.webp",
  duoPlatformStraight: "assets/duo/gameplay/tiles/platform_straight.webp",
};
export const assets = {
  ...optimizedAssets,
  ...snakeAssets,
  ...dashAssets,
  ...duoAssets,
};
